[pytest]
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
testpaths = tests
addopts = -p no:cacheprovider
filterwarnings =
    ignore:'oneOf' deprecated - use 'one_of':DeprecationWarning:matplotlib\._fontconfig_pattern
    ignore:'parseString' deprecated - use 'parse_string':DeprecationWarning:matplotlib\._fontconfig_pattern
    ignore:'resetCache' deprecated - use 'reset_cache':DeprecationWarning:matplotlib\._fontconfig_pattern
    ignore:'enablePackrat' deprecated - use 'enable_packrat':DeprecationWarning:matplotlib\._mathtext
    ignore:Using slow pure-python SequenceMatcher.*:UserWarning:fuzzywuzzy\.fuzz
    ignore:'audioop' is deprecated and slated for removal in Python 3\.13:DeprecationWarning:discord\.player
